<div style="width:134px; height:160px; float:left; margin-right:13px;">
                        <div style="height:134px;"><a title="[field:title/]" href="[field:arcurl/]"><img alt="wellest-stone" src="[field:litpic/]" width="134" height="134" /></a></div>
                        <div style="line-height:25px; height:25px; overflow:hidden; text-align:center;"><a href="[field:arcurl/]">[field:title/]</a></div>
                      </div>