<?php
$z[0]=Array("arcurl","",48,63);
$z[1]=Array("title","",72,86);
$z[2]=Array("litpic","",98,113);
$z[3]=Array("title","",121,135);
$z[4]=Array("title","",144,158);
$z[5]=Array("arcurl","",277,292);
$z[6]=Array("title","",301,315);
$z[7]=Array("title","",317,331);
$z[8]=Array("pubdate","",357,404);
$z[8][4]['function']="MyDate('Y-m-d',@me)";
$z[9]=Array("description","",446,496);
$z[9][4]['function']="cn_substr(@me,160)";
$z[10]=Array("arcurl","",544,559);
$z[11]=Array("title","",568,582);

?>