<li>
      <div class="khjz_m"><a href="[field:arcurl/]" title="[field:title/]"><img src="[field:litpic/]"  alt="[field:title/]" title="[field:title/]" width="191" height="145"/></a></div>
      <div class="khjz_r">
        <div class="jz_rt">
          <p><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a></p>
          <span>[field:pubdate function="MyDate('Y-m-d',@me)"/]</span></div>
        <div class="jz_rp">[field:description function="cn_substr(@me,140)"/]。。。。。</div>
        <div class="jz_rb"><a href="[field:arcurl/]" title="[field:title/]"><img src="/skin/images/rc_24.jpg" width="70" height="16" alt="" /></a></div>
      </div>
    </li>