<?php
$z[0]=Array("arcurl","",41,56);
$z[1]=Array("title","",65,79);
$z[2]=Array("litpic","",91,106);
$z[3]=Array("title","",114,128);
$z[4]=Array("title","",137,151);
$z[5]=Array("arcurl","",270,285);
$z[6]=Array("title","",294,308);
$z[7]=Array("title","",310,324);
$z[8]=Array("pubdate","",350,397);
$z[8][4]['function']="MyDate('Y-m-d',@me)";
$z[9]=Array("description","",439,489);
$z[9][4]['function']="cn_substr(@me,140)";
$z[10]=Array("arcurl","",548,563);
$z[11]=Array("title","",572,586);

?>