
<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:tel itemname="电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:tel>

<field:neirong itemname="留言内容" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:neirong>

<field:email itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="100" page="">
</field:email>
