<?php
$z[0]=Array("channel","\r\n<li>&nbsp;&nbsp;&nbsp;<a href=\"[field:typeurl /]\" id=\"lmt[field:id /]\">[field:typename /]</a></li>\r\n",380,541);
$z[0][4]['type']="sun";
$z[0][4]['row']="";
$z[0][4]['typeid']="85";
$z[1]=Array("channel","\r\n<li>&nbsp;&nbsp;&nbsp;<a href=\"[field:typeurl /]\" id=\"lmt[field:id /]\">[field:typename /]</a></li>\r\n",736,897);
$z[1][4]['type']="sun";
$z[1][4]['row']="";
$z[1][4]['typeid']="78";
$z[2]=Array("channel","\r\n<li>&nbsp;&nbsp;&nbsp;<a href=\"[field:typeurl /]\" id=\"lmt[field:id /]\">[field:typename /]</a></li>\r\n",1088,1249);
$z[2][4]['type']="sun";
$z[2][4]['row']="";
$z[2][4]['typeid']="73";
$z[3]=Array("channel","\r\n<li>&nbsp;&nbsp;&nbsp;<a href=\"[field:typeurl /]\" id=\"lmt[field:id /]\">[field:typename /]</a></li>\r\n",1466,1627);
$z[3][4]['type']="sun";
$z[3][4]['row']="";
$z[3][4]['typeid']="64";
$z[4]=Array("channel","\r\n<li>&nbsp;&nbsp;&nbsp;<a href=\"[field:typeurl /]\" id=\"lmt[field:id /]\">[field:typename /]</a></li>\r\n",1829,1990);
$z[4][4]['type']="sun";
$z[4][4]['row']="";
$z[4][4]['typeid']="50";
$z[5]=Array("channel","\r\n<li>&nbsp;&nbsp;&nbsp;<a href=\"[field:typeurl /]\" id=\"lmt[field:id /]\">[field:typename /]</a></li>\r\n",2191,2352);
$z[5][4]['type']="sun";
$z[5][4]['row']="";
$z[5][4]['typeid']="49";

?>