<?php
$z[0]=Array("channel","\r\n<li>&nbsp;&nbsp;&nbsp;<a href=\"[field:typeurl /]\" id=\"lmt[field:id /]\">[field:typename /]</a></li>\r\n",380,541);
$z[0][4]['type']="sun";
$z[0][4]['row']="";
$z[0][4]['typeid']="85";
$z[1]=Array("channel","\r\n<li>&nbsp;&nbsp;&nbsp;<a href=\"[field:typeurl /]\" id=\"lmt[field:id /]\">[field:typename /]</a></li>\r\n",733,894);
$z[1][4]['type']="sun";
$z[1][4]['row']="";
$z[1][4]['typeid']="78";
$z[2]=Array("channel","\r\n<li>&nbsp;&nbsp;&nbsp;<a href=\"[field:typeurl /]\" id=\"lmt[field:id /]\">[field:typename /]</a></li>\r\n",1085,1246);
$z[2][4]['type']="sun";
$z[2][4]['row']="";
$z[2][4]['typeid']="73";
$z[3]=Array("channel","\r\n<li>&nbsp;&nbsp;&nbsp;<a href=\"[field:typeurl /]\" id=\"lmt[field:id /]\">[field:typename /]</a></li>\r\n",1458,1619);
$z[3][4]['type']="sun";
$z[3][4]['row']="";
$z[3][4]['typeid']="64";
$z[4]=Array("channel","\r\n<li>&nbsp;&nbsp;&nbsp;<a href=\"[field:typeurl /]\" id=\"lmt[field:id /]\">[field:typename /]</a></li>\r\n",1821,1982);
$z[4][4]['type']="sun";
$z[4][4]['row']="";
$z[4][4]['typeid']="50";
$z[5]=Array("channel","\r\n<li>&nbsp;&nbsp;&nbsp;<a href=\"[field:typeurl /]\" id=\"lmt[field:id /]\">[field:typename /]</a></li>\r\n",2183,2344);
$z[5][4]['type']="sun";
$z[5][4]['row']="";
$z[5][4]['typeid']="49";

?>