<?php
$z[0]=Array("channelartlist","\r\n			<li class=\"mainlevel\" id=\"mainlevel_0[field:global.autoindex/]\">\r\n				<p>\r\n					<a href=\"{dede:field name='typeurl'/}\" title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a>\r\n					<ul id=\"sub_01\" class=\"menual\">\r\n						{dede:channel type='son' noself='yes'}\r\n						<li>\r\n							<a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n						</li>\r\n						{/dede:channel}\r\n					</ul>\r\n				</p>\r\n			</li>\r\n			",975,1459);
$z[0][4]['typeid']="47";
$z[0][4]['row']="6";
$z[1]=Array("arclist","\r\n			<li><img src=\"[field:litpic/]\" alt=\"[field:title/]\" title=\"[field:title/]\"/></li>\r\n			",1547,1727);
$z[1][4]['row']="4";
$z[1][4]['typeid']="14";
$z[1][4]['orderby']="id";
$z[1][4]['orderway']="asc";
$z[1][4]['titlelen']="90";

?>