<?php
$z[0]=Array("global","",254,280);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",321,343);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",383,434);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",1053,1094);
$z[3][4]['filename']="en_head_1.htm";
$z[4]=Array("include","",1116,1154);
$z[4][4]['filename']="en_left.htm";
$z[5]=Array("field","",1235,1264);
$z[5][4]['name']="typename";
$z[6]=Array("field","\r\n\$b = array(\"主页\");\r\n\$c = array(\"HOME\");\r\n@me=str_replace(\$b,\$c,@me);\r\n",1286,1415);
$z[6][4]['name']="position";
$z[6][4]['runphp']="yes";
$z[7]=Array("field","",1500,1521);
$z[7][4]['name']="content";
$z[8]=Array("include","",1548,1588);
$z[8][4]['filename']="en_footer.htm";

?>