<?php
$z[0]=Array("global","",254,280);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",321,343);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",383,434);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("include","",1053,1094);
$z[3][4]['filename']="en_head_1.htm";
$z[4]=Array("include","",1116,1154);
$z[4][4]['filename']="en_left.htm";
$z[5]=Array("list","\r\n        <dd>\r\n          <div class=\"img cssimg\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\"><img src=\"[field:litpic/]\" title=\"[field:title/]\" /></a></div>\r\n          <div class=\"txt\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></div>\r\n        </dd>\r\n        ",1233,1556);
$z[5][4]['pagesize']="12";
$z[6]=Array("pagelist","",1644,1710);
$z[6][4]['listsize']="5";
$z[6][4]['listitem']="index,end,pre,next,pageno";
$z[7]=Array("include","",1763,1803);
$z[7][4]['filename']="en_footer.htm";

?>