<?php
$z[0]=Array("field","",471,522);
$z[0][4]['name']="typeid";
$z[0][4]['function']="GetTopTypename(@me)";
$z[1]=Array("field","",595,647);
$z[1][4]['name']="typeid";
$z[1][4]['function']="gettoptype(@me,name)";
$z[2]=Array("channel","\r\n						<li>\r\n							<a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n						</li>\r\n						",672,815);
$z[2][4]['type']="son";
$z[2][4]['noself']="yes";

?>