<?php
$z[0]=Array("channel","\r\n<li>&nbsp;&nbsp;&nbsp;<a href=\"[field:typeurl /]\" id=\"lmt[field:id /]\">[field:typename /]</a></li>\r\n",378,538);
$z[0][4]['type']="sun";
$z[0][4]['row']="";
$z[0][4]['typeid']="5";
$z[1]=Array("channel","\r\n<li>&nbsp;&nbsp;&nbsp;<a href=\"[field:typeurl /]\" id=\"lmt[field:id /]\">[field:typename /]</a></li>\r\n",736,896);
$z[1][4]['type']="sun";
$z[1][4]['row']="";
$z[1][4]['typeid']="2";
$z[2]=Array("channel","\r\n<li>&nbsp;&nbsp;&nbsp;<a href=\"[field:typeurl /]\" id=\"lmt[field:id /]\">[field:typename /]</a></li>\r\n",1095,1255);
$z[2][4]['type']="sun";
$z[2][4]['row']="";
$z[2][4]['typeid']="3";
$z[3]=Array("channel","\r\n<li>&nbsp;&nbsp;&nbsp;<a href=\"[field:typeurl /]\" id=\"lmt[field:id /]\">[field:typename /]</a></li>\r\n",1464,1624);
$z[3][4]['type']="sun";
$z[3][4]['row']="";
$z[3][4]['typeid']="4";
$z[4]=Array("channel","\r\n<li>&nbsp;&nbsp;&nbsp;<a href=\"[field:typeurl /]\" id=\"lmt[field:id /]\">[field:typename /]</a></li>\r\n",1828,1988);
$z[4][4]['type']="sun";
$z[4][4]['row']="";
$z[4][4]['typeid']="1";
$z[5]=Array("channel","\r\n<li>&nbsp;&nbsp;&nbsp;<a href=\"[field:typeurl /]\" id=\"lmt[field:id /]\">[field:typename /]</a></li>\r\n",2193,2353);
$z[5][4]['type']="sun";
$z[5][4]['row']="";
$z[5][4]['typeid']="6";

?>