<?php
$z[0]=Array("channel","\r\n<li>&nbsp;&nbsp;&nbsp;<a href=\"[field:typeurl /]\" id=\"lmt[field:id /]\">[field:typename /]</a></li>\r\n",379,539);
$z[0][4]['type']="sun";
$z[0][4]['row']="";
$z[0][4]['typeid']="5";
$z[1]=Array("channel","\r\n<li>&nbsp;&nbsp;&nbsp;<a href=\"[field:typeurl /]\" id=\"lmt[field:id /]\">[field:typename /]</a></li>\r\n",758,918);
$z[1][4]['type']="sun";
$z[1][4]['row']="";
$z[1][4]['typeid']="2";
$z[2]=Array("channel","\r\n<li>&nbsp;&nbsp;&nbsp;<a href=\"[field:typeurl /]\" id=\"lmt[field:id /]\">[field:typename /]</a></li>\r\n",1117,1277);
$z[2][4]['type']="sun";
$z[2][4]['row']="";
$z[2][4]['typeid']="3";
$z[3]=Array("channel","\r\n<li>&nbsp;&nbsp;&nbsp;<a href=\"[field:typeurl /]\" id=\"lmt[field:id /]\">[field:typename /]</a></li>\r\n",1487,1647);
$z[3][4]['type']="sun";
$z[3][4]['row']="";
$z[3][4]['typeid']="4";
$z[4]=Array("channel","\r\n<li>&nbsp;&nbsp;&nbsp;<a href=\"[field:typeurl /]\" id=\"lmt[field:id /]\">[field:typename /]</a></li>\r\n",1851,2011);
$z[4][4]['type']="sun";
$z[4][4]['row']="";
$z[4][4]['typeid']="1";
$z[5]=Array("channel","\r\n<li>&nbsp;&nbsp;&nbsp;<a href=\"[field:typeurl /]\" id=\"lmt[field:id /]\">[field:typename /]</a></li>\r\n",2214,2374);
$z[5][4]['type']="sun";
$z[5][4]['row']="";
$z[5][4]['typeid']="6";

?>