<?php
$z[0]=Array("flink","[field:link /]",79,153);
$z[0][4]['titlelen']="20";
$z[0][4]['row']="10";
$z[0][4]['type']="text";
$z[1]=Array("channel","\r\n        \r\n        ·<a href=\"[field:typeurl/]\"  title=\"[field:typename/]\">[field:typename/]</a> ",295,433);
$z[1][4]['type']="top";
$z[2]=Array("global","",477,503);
$z[2][4]['name']="cfg_powerby";
$z[3]=Array("global","",529,553);
$z[3][4]['name']="cfg_beian";
$z[4]=Array("global","",586,607);
$z[4][4]['name']="cfg_dh";
$z[5]=Array("global","",634,655);
$z[5][4]['name']="cfg_sj";
$z[6]=Array("global","",685,706);
$z[6][4]['name']="cfg_dz";

?>