<?php
$z[0]=Array("global","",77,98);
$z[0][4]['name']="cfg_dh";
$z[1]=Array("global","",114,135);
$z[1][4]['name']="cfg_sj";
$z[2]=Array("channelartlist","\r\n      <li class=\"mainlevel\" id=\"mainlevel_0[field:global.autoindex/]\" >\r\n        <p><a href=\"{dede:field name='typeurl'/}\"  title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a>\r\n        <ul id=\"sub_01\" class=\"menual\">\r\n          {dede:channel type='son' noself='yes'}\r\n          <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n          {/dede:channel}\r\n        </ul>\r\n        </p>\r\n      </li>\r\n      ",442,932);
$z[2][4]['typeid']="top";
$z[3]=Array("arclist","\r\n      <li><img src=\"[field:litpic/]\"  alt=\"[field:title/]\" title=\"[field:title/]\" width=\"1900\" height=\"565\"/></li>\r\n      ",1029,1198);
$z[3][4]['row']="3";
$z[3][4]['typeid']="14";

?>