<?php
$z[0]=Array("channelartlist","\r\n      <li class=\"mainlevel\" id=\"mainlevel_0[field:global.autoindex/]\" >\r\n        <p><a href=\"{dede:field name='typeurl'/}\"  title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a>\r\n        <ul id=\"sub_01\" class=\"menual\">\r\n          {dede:channel type='son' noself='yes'}\r\n          <li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n          {/dede:channel}\r\n        </ul>\r\n        </p>\r\n      </li>\r\n      ",1102,1592);
$z[0][4]['typeid']="top";

?>