<?php
$z[0]=Array("channelartlist","\r\n			<li class=\"mainlevel\" id=\"mainlevel_0[field:global.autoindex/]\">\r\n				<p>\r\n					<a href=\"{dede:field name='typeurl'/}\" title=\"{dede:field name='typename'/}\">{dede:field name='typename'/}</a>\r\n					<ul id=\"sub_01\" class=\"menual\">\r\n						{dede:channel type='son' noself='yes'}\r\n						<li>\r\n							<a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n						</li>\r\n						{/dede:channel}\r\n					</ul>\r\n				</p>\r\n			</li>\r\n			",1000,1477);
$z[0][4]['typeid']="top";
$z[1]=Array("arclist","\r\n			<li><img src=\"[field:litpic/]\" alt=\"[field:title/]\" title=\"[field:title/]\" width=\"1920\" height=\"580\" /></li>\r\n			",1565,1728);
$z[1][4]['row']="4";
$z[1][4]['typeid']="14";

?>