<?php
$z[0]=Array("global","",219,245);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("include","",1167,1206);
$z[1][4]['filename']="header_m.htm";
$z[2]=Array("field","",1503,1532);
$z[2][4]['name']="typename";
$z[3]=Array("channel","\r\n        <li><a href=\"list.php?tid=[field:id/]\" title=\"[field:typename/]\">[field:typename/]</a> <span class=\"commonfont class-down\"></span></li>\r\n        ",1757,2085);
$z[3][4]['type']="son";
$z[3][4]['row']="10";
$z[3][4]['currentstyle']="<li class='hover'><a href='list.php?tid=~id~' ~rel~><span>~typename~</span></a> </li>";
$z[4]=Array("field","",2255,2276);
$z[4][4]['name']="content";
$z[5]=Array("include","",2331,2370);
$z[5][4]['filename']="footer_m.htm";

?>