<?php
$z[0]=Array("field","",465,517);
$z[0][4]['name']="typeid";
$z[0][4]['function']="gettoptype(@me,link)";
$z[1]=Array("field","",543,602);
$z[1][4]['name']="typeid";
$z[1][4]['function']="GetTopTypename(@me)";
$z[2]=Array("field","",679,731);
$z[2][4]['name']="typeid";
$z[2][4]['function']="gettoptype(@me,name)";
$z[3]=Array("channel","\r\n						<li>\r\n							<a href=\"[field:typeurl/]\">[field:typename/]</a>\r\n						</li>\r\n						",756,899);
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";

?>