<?php
$z[0]=Array("field","",141,199);
$z[0][4]['name']="typeid";
$z[0][4]['function']="GetTopTypename(@me)";
$z[1]=Array("channel","\r\n        <dd><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a></dd>\r\n        ",214,356);
$z[1][4]['type']="son";
$z[2]=Array("arclist","\r\n    <div class=\"tcp\"> <a href=\"[field:arcurl/]\" title=\"[field:title/]\"> <img src=\"[field:litpic/]\"  alt=\"[field:title/]\" title=\"[field:title/]\"/>\r\n      <p>[field:title/]</p>\r\n      </a> </div>\r\n    ",464,709);
$z[2][4]['row']="2";
$z[2][4]['typeid']="1";
$z[3]=Array("global","",902,923);
$z[3][4]['name']="cfg_dh";
$z[4]=Array("global","",998,1019);
$z[4][4]['name']="cfg_sj";
$z[5]=Array("global","",1049,1070);
$z[5][4]['name']="cfg_dz";

?>