<?php
$typeArr[1] = '产品中心';
$typeArr[2] = '技术支持';
$typeArr[3] = '新闻资讯';
$typeArr[4] = '应用领域';
$typeArr[5] = '联系我们';
$typeArr[6] = '关于我们';
$typeArr[7] = 'Facility Tour';
$typeArr[8] = 'Manufacturing Capability';
$typeArr[11] = 'EMS';
$typeArr[12] = 'PCB';
$typeArr[13] = 'PCB Assembly';
$typeArr[14] = 'banner';
$typeArr[15] = 'R&D Capability';
$typeArr[16] = 'Process Control';
$typeArr[18] = 'Engineering Design';
$typeArr[19] = 'About SMT technology';
$typeArr[20] = 'PCB surface treatment';
$typeArr[21] = 'PADS 9.5';
$typeArr[22] = 'PCB Material Information';
$typeArr[23] = 'Through-hole technology';
$typeArr[24] = 'PCB Layout Design';
$typeArr[25] = 'Products OEM/ODM';
$typeArr[26] = 'Final Assembly';
$typeArr[27] = 'Flexible PCBA';
$typeArr[28] = 'PCBA';
?>